### ISSUE TITLE
capitalize `Access` class

### ISSUE THREAD

**Issue by knaaptime** [pysal/access#10]
since we want to [ensure pep-8 compatibility](https://pysal.org/getting_started) across the subpackages,  could we [capitalize](https://www.python.org/dev/peps/pep-0008/#id41) the `Access` class?

**Comment by JamesSaxon** [comment]
Sure, we can do this, but it will take me a few days to get to this.  Vidal brought this up earlier.

**Comment by JamesSaxon** [comment]
Hey, @knaaptime --- yes that has been on my mind.

@jkoschinsky and I had said that @vidal-anguiano would look at this, but it has been some time.  @vidal-anguiano, do you expect to have time for this before January?

**Comment by knaaptime** [comment]
sweet! (sorry to pester :)) 

i've got some other maintenance to do for other packages before the meta release as well, so I'm happy to help put the PR together too, if that's the path of least resistance

**Comment by vidal-anguiano** [comment]
@knaaptime, @jkoschinsky  and @JamesSaxon , apologies for the delay on this, I've made the case changes to both the `Access` and `Datasets` classes, and created a [pull request](https://github.com/pysal/access/pull/15). Let me know if you have any feedback or see anything I might have missed!
