### ISSUE TITLE
[ENH] versioneer for versioning

### ISSUE THREAD

**Issue by knaaptime** [pysal/access#21]
in the rest of the ecosystem we're [using versioneer](https://github.com/pysal/libpysal/pull/429) to handle the `__version__` attribute. We want to do the same here

**Comment by JamesSaxon** [comment]
Hey @knaaptime, I'll try to get to this next weekend or so.  Is the recipe outlined by @martinfleis still up to date?

* https://github.com/pysal/libpysal/pull/429

**Comment by martinfleis** [comment]
Yes, it should be fine.

**Comment by jGaboardi** [comment]
@JamesSaxon I might have time tomorrow to do this.

Also, I suggest we adopt [`black`](https://github.com/psf/black) format for the repo as we have done in most other PySAL modules. By going with `black` we don't have to worry about formatting and only focus on code. Plus we can implement a [`pre-commit` hook to run `black` for every commit](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/).

**Comment by jGaboardi** [comment]
let's hold off for this. the ecosystem is migrating towards `setuptools_scm` for versioning.

**Comment by jGaboardi** [comment]
Closing out per #48
