### ISSUE TITLE
generate pypi token for Secret in GH

### ISSUE THREAD

**Issue by jGaboardi** [pysal/access#29]
@JamesSaxon The release workflow is failing due to a bad [PyPI token](https://github.com/pysal/access/runs/6437036021?check_suite_focus=true#step:6:13). This need to be created in PyPI and included in [Secrets](https://github.com/pysal/access/settings/secrets/actions). [Here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) is a guide.

**Comment by JamesSaxon** [comment]
Added the secrets --

<img width="214" alt="image" src="https://user-images.githubusercontent.com/12751805/168453660-41d35832-b6ed-4086-9141-6f181ac6e565.png">

All set?  Or should I have named this `pypi_password` as in [the workflow](https://github.com/pysal/access/blob/85e9b1609ca6e9eb93b60984ac09d54011783e9d/.github/workflows/upload_package.yml#L27)?

**Comment by jGaboardi** [comment]
Yep, let's rename to `pypi_password` (the convention seems to generally be to have these in all caps, but it shouldn't make a difference as long as the secret name matches the workflow name. Also, we can get rid of the `TEST` secret. Once this is done, I will try the release again.

**Comment by JamesSaxon** [comment]
Done.  The capitalization reverted to all caps after submitting (tested this again, to confirm), so that seems to be enforced on the GitHub side.
