### ISSUE TITLE
release + upload workflow failure

### ISSUE THREAD

**Issue by jGaboardi** [pysal/access#31]
The [`upload_package.yml`](https://github.com/pysal/access/blob/v1.1.6/.github/workflows/upload_package.yml) workflow is failing seemingly due to [`v1.1.3` being pushed to PyPI](https://github.com/pysal/access/runs/6445135712?check_suite_focus=true#step:6:13), though I am pushing `v1.1.6`. Maybe it's a problem with ordering in the workflow because the push to PyPI happens before the release creation, though this was not an issue previously...

**Comment by JamesSaxon** [comment]
I think if it were just a race condition on building the package, then re-triggering the build would run OK.  It still fails. 

So it looks like the version is still defined here, after the infrastructure reorganization.

https://github.com/pysal/access/blob/e235afb04778fb8e1f77509eee8be36f4f7a1c84/access/__init__.py#L1

I changed that to 1.1.6; if that's all, could you re-build and relaunch?  Thanks @jGaboardi for all this work.  

When it is set, I'd like to know the sequence, so I can handle that for future updates (like Eli's proposed #27).

**Comment by jGaboardi** [comment]
Ahh, because we hadn't set up `versioneer` for this. My oversight.

**Comment by jGaboardi** [comment]
@JamesSaxon, I just deleted the `v1.1.6` tag here and locally, then recreated it to include the version bump you made (good catch). To triggered the release action a tag starting with `"v"` has to be created locally and pushed upstream. This done like so:

```
$ git tag -a v1.1.6 -m "v1.1.6"
git push upstream v1.1.6
```

**Comment by jGaboardi** [comment]
@JamesSaxon I *finally* got it worked out. Sorry for the delay!

**Comment by JamesSaxon** [comment]
Thanks @jGaboardi for all this work!  Hopefully this sets us up for subsequent upgrade -- yes!?

As I understood your last comment, the process will be:
* do stuff
* change version number (?)
* push corresponding tag.
