### ISSUE TITLE
[2SFCA/3SFCA] KeyError: 'xxx_W'

### ISSUE THREAD

**Issue by alexandermichels** [pysal/access#34]
I ran into this issue while using the Pysal Access package today, when using two or three stage FCA models, you end up with the key error in the title where it is unable to find a column of the form `<demand value>_W`. You can see two such errors below:

Two Stage FCA:
![WError](https://user-images.githubusercontent.com/36479843/171039360-90fe13ed-868b-4ee5-b43e-74f1c8e20591.png)

Three Stage FCA
![3SFCAError](https://user-images.githubusercontent.com/36479843/171039350-5c7b8f33-1f39-4556-b05c-3ab7097b0218.png)

The errors above are from a [tutorial notebook](https://github.com/pysal/access/blob/master/notebooks/Generating%20and%20Plotting%20a%20Variety%20of%20Access%20Scores.ipynb), [seen here on nbgitviewer](https://nbviewer.org/github/pysal/access/blob/master/notebooks/Generating%20and%20Plotting%20a%20Variety%20of%20Access%20Scores.ipynb)

From looking over the code, it would seem that `weighted_catchment` (in fca.py) used to return a series with the name `<demand value>_W`, but does not any longer. The offending line in `two_stage_fca` [is here](https://github.com/pysal/access/blob/master/access/fca.py#L224). This is a quick fix and I'll submit a PR, but opening the issue here in case others run into it.

**Comment by JamesSaxon** [comment]
Closed #36
